# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d370670bae31d5152ab9b44eb79eeab2ff1cc523ca64be72175327ce5ea29eec430e1d030e4a1976545cce276f780b72c3a9b9c27b3a7c1e7a1d743c1db5357e

test:
  secret_key_base: a07831e38b38c08009574ea6c9647907cc9ab482a52db10e00115ea8b81acf0fac46eff951b8235a456c2fb60471a105800902e4830f5ae08066cc653cefdf18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
